server:
  port: 0

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
      circuitbreaker:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/requests-db
    username: dbuser
    password: 12345

grpc:
  client:
    collector:
      address: discovery:///COLLECTOR
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
    analyzer:
      address: discovery:///ANALYZER
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true