server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: events_service_route
          uri: lb://events-service
          predicates:
#           - Path=/events/** , /admin/events/**, /*/events/**, /*/comments/**, /users/*/events/**
           - Path=/events/**, /admin/events/**, /*/events/**, /*/comments, /*/comments/**, /comments/**, /users/*/events/**

        - id: users_service_route
          uri: lb://users-service
          predicates:
           - Path=/admin/users/**

        - id: extra_service_route
          uri: lb://category-service
          predicates:
           - Path=/compilations/**, /categories/**, /admin/categories/**, /admin/compilations/**

        - id: requests_service_route
          uri: lb://requests-service
          predicates:
           - Path=/users/{userId}/requests/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route: DEBUG