server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: ewm_main_service_route
          uri: lb://main-service
          predicates:
            - Path=/events/**,/categories/**,/compilations/**,/users/**,/admin/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route: DEBUG