server:
  port: 0

grpc:
  server:
    port: 0

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aggregator-group
      auto-offset-reset: earliest
    producer:
      client-id: aggregator-producer